name: CI

on:
  push:
    branches: [ "main", "pipeline" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      env:
        AzureOpenAI__ChatDeploymentName: ${{ secrets.IntegrationTest__AzureOpenAI__ChatDeploymentName }}
        AzureOpenAI__TextEmbeddingsDeploymentName: ${{ secrets.IntegrationTest__AzureOpenAI__TextEmbeddingsDeploymentName }}
        AzureOpenAI__Endpoint: ${{ secrets.IntegrationTest__AzureOpenAI__Endpoint }}
        AzureOpenAI__ApiKey: ${{ secrets.IntegrationTest__AzureOpenAI__ApiKey }}
      run: dotnet test --no-build --verbosity normal
